server.port=8080
spring.application.name=Fitness Nutrition Advisor Web
spring.web.resources.cache.period=0
spring.jackson.serialization.indent-output=true
logging.level.bg.uniplov.fitness.advisor=INFO
